"""Agent state definition for multi-agent workflow.

This module defines the AgentState TypedDict that is shared across all
LangGraph agent nodes. The state tracks the user's query, retrieved context,
agent outputs, and metadata throughout the workflow.
"""

from typing import Any, TypedDict


class AgentState(TypedDict):
    """State shared across all agent nodes.

    All fields must be explicitly typed and documented.
    LangGraph automatically merges partial state updates from nodes.

    Attributes:
        query: User's original question
        session_id: Unique session identifier for conversation tracking
        memory_summary: Condensed summary of conversation history
        memory_messages: Recent message turns (format: "Role: content")
        retrieved_docs: Documents retrieved from RAG pipeline with metadata
        draft_answer: Initial answer generated by draft agent (None until created)
        critique: Feedback from critique agent (None until created)
        final_answer: Final refined answer after critique
        confidence: Confidence score between 0.0 and 1.0
        sources: List of source documents with title and url for attribution
        escalated: Whether the question was escalated to HR team
    """

    # Input
    query: str

    # Session and memory
    session_id: str
    memory_summary: str
    memory_messages: list[str]

    # Retrieved context
    retrieved_docs: list[dict[str, Any]]

    # Agent outputs
    draft_answer: str | None
    critique: str | None
    final_answer: str
    confidence: float

    # Output metadata
    sources: list[dict[str, str]]
    escalated: bool
